<?php
/**
 * @var $this Elgentos\BackendLauncher\Block\LauncherItems
 */
?>

<script type="text/javascript">
var launcher_items = <?php echo $this->getItemsJson(); ?>;
var launcher_keyboard_sequence_a = '<?php echo $this->getFirstSequenceKey(); ?>';
var launcher_keyboard_sequence_b = '<?php echo $this->getSecondSequenceKey(); ?>';
</script>

<div id="elgentos-backendlauncher-dialog" title="Launcher">
    <input placeholder="Awaiting command." type="text" id="elgentos-backendlauncher-input" />
</div>